# Generated by Django 3.0.5 on 2023-01-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='fee',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='salary',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
